* My GNU/Emacs configuration folder

** General Structure

In my $HOME, there is this folder named "~/.emacs.d". It contains a
symbolic link "init.el" which points to the host-specific
"init-HOSTNAME.el" file.

My "init-HOSTNAME.el" files are very minimal. Each one holds
custom-set-variables which I want to keep separate on each host. And
then it includes the host-independent "main.el" configuration file.

Please take a look at my ".gitignore" file that contains some things I
did *not* add to this git repository for a variety of reasons but are
necessary for my configuration. Most important here is the directory
"contrib" which holds a number of external packages:

- Currently (2014-01-19), this directory holds:
  - [[https://github.com/lewang/command-log-mode][command-log-mode]]/
  - [[http://randomsample.de/minimap.git][minimap]]/
  - [[http://Orgmode.org][org-mode]]/
  - [[http://taesoo.org/proj/pylookup.html][pylookup]]/
  - [[https://raw.github.com/vjohansen/emacs-config/master/org-import-calendar.el][org-import-calendar.el]]
  - [[http://www.emacswiki.org/emacs/wc.el][wc.el]]
    
** Host-Names

Some settings as specific for certain platforms or host names. The
host names mentioned here are:

- gary
  - Debian GNU/Linux Wheezy
  - my main working horse

- blanche
  - OS X 10.5
  - pimped with [[https://www.macports.org/][MacPorts]]
    - (therefore) not as "capable" as gary

- grmlvrs
  - Debian GNU/Linux stable 5.0
    - (therefore) not as "capable" as gary

- atgrz*
  - Windows 7 Pro with native Windows GNU/Emacs 64bit
    - (therefore) not as "capable" as gary

** Emacs 24

As with 2014-01-19, I totally migrated to GNU/Emacs 24 on all of my
systems.

I therefore migrated my config to use the package management provided
by Emacs 24. As a result, there are much less entries in the folder
"contrib" and there is a new folder called "elpa". I did not include
elpa-packages in this git repository.

On 2014-01-19, I had following packages installed via elpa:

#+BEGIN_SRC sh :exports results :results output
ls -1 ~/.emacs.d/elpa
#+END_SRC

#+RESULTS:
#+begin_example
ace-jump-mode-20130719.2053
ack-and-a-half-20130815.1917
anzu-20131119.1848
archives
auctex-11.87.2
auto-complete-20131128.233
boxquote-1.23
browse-kill-ring-20131116.2113
dash-20131223.933
deferred-20130930.607
diminish-20091203.1012
elisp-slime-nav-20130612.446
elpy-20131109.1120
elpy-readme.txt
epl-20131101.405
expand-region-20131111.329
f-20131225.721
find-file-in-project-20120716.1655
flx-20130728.820
flx-ido-20131030.1243
flycheck-20131224.546
fuzzy-20131025.2343
gh-20131223.2140
gist-20131109.2155
git-commit-mode-20131230.729
gitconfig-mode-20131221.230
gitignore-mode-20131222.833
git-rebase-mode-20131223.1820
grizzl-20130810.202
guru-mode-20121016.452
helm-20131230.2118
helm-projectile-20131209.505
highlight-indentation-20131207.835
idomenu-20111122.1048
ido-ubiquitous-20131009.1047
iedit-20131021.116
logito-20120225.1255
magit-20131230.611
mediawiki-20130223.1141
move-text-20130506.1826
nose-20110804.619
pcache-20131201.1159
pkg-info-20131101.408
popup-20131230.544
projectile-20131230.851
pydoc-info-readme.txt
python-info-readme.txt
rainbow-delimiters-20131015.404
rainbow-mode-0.9
s-20131223.944
smartparens-20131230.514
smex-20131210.700
solarized-theme-20131221.1216
tabulated-list-20120406.1351
undo-tree-20131118.1744
virtualenv-20120930.1034
volatile-highlights-20130321.641
yasnippet-20131224.143
zenburn-theme-20131228.1447
#+end_example

Some of them are not used any more because they got installed by [[https://github.com/bbatsov/prelude][Emacs
prelude]] which I tested for a couple of days. However, I was not very
happy about it due to performance issues and unwanted behavior.

** Useful References

- http://www.emacswiki.org/emacs/CategoryDotEmacs
- http://www.emacswiki.org/emacs/LoadPath
  - ~/.emacs.d/lisp/ seems to be quite common as directory path for
    installing external packages
  - However, I do prefer "contrib" instead of "lisp" because:
    - my own config (outside of ~/.emacs.d/lisp/) is LISP as well
    - "lisp" does not contain the notion of "contributed from other people/projects"
** License

The code provided here is licensed under a GPL v3 license: see
license.txt for details. Some smaller parts from other authors but
included in my configuration might have a different license. Please
check the source - it's included in the comments.


