* My GNU/Emacs configuration folder

** General Structure

In my $HOME, there is a symlink from
"~/.emacs.d/dot-emacs-HOSTNAME.el" to "~/.emacs".

My ".emacs" files are very minimal. Each ".emacs" holds
custom-set-variables which I want to keep separate on each host. And
then it includes the host-independent "main.el" configuration file.

So far, I still separate "main.el" and "org-mode.el". This is because
my [[http://Orgmode.org][Org-mode]] configuration is pretty huge. However, I plan to combine
both using [[http://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming][Emacs Initialization with Babel]].

Please take a look at my ".gitignore" file that contains some things I
did *not* add to this git repository for a variety of reasons but are
necessary for my configuration. Most important here is the directory
"contrib" which holds a number of external packages:

- Currently (2013-01-20), this directory holds:
  - [[https://github.com/sellout/emacs-color-theme-solarized][emacs-color-theme-solarized]]/
  - [[http://Orgmode.org][org-mode]]/
  - [[http://www.dr-qubit.org/git/undo-tree.git][undo-tree]]/
  - [[https://github.com/capitaomorte/yasnippet][yasnippet/]]
  - [[http://www.davep.org/emacs/#boxquote.el][boxquote.el]]
  - [[http://www.emacswiki.org/emacs/wc.el][wc.el]]
- Also in this directory but deactivated or not used by me:
  - [[https://github.com/kiwanami/emacs-calfw][calfw]]/
  - [[https://code.google.com/p/emacs-open-resource/source/browse/trunk/open-resource.el?r%3D2][emacs-open-resource-read-only]]/
  - [[http://www.randomsample.de/minimap.el][minimap]]/
  - [[http://github.com/hayamiz/twittering-mode][twittering-mode]]/
  - [[http://www.emacswiki.org/tabbar.el][tabbar.el]]
  - [[http://edward.oconnor.cx/elisp/growl.el][growl.el]]
  - [[http://www.neilvandyke.org/erin-twiki-emacs/][erin.el]]
  - [[http://www.emacswiki.org/emacs/EmacsEchoServer][edit-server.el]]
  - [[http://www.mfasold.net/blog/2009/02/using-emacs-org-mode-to-draft-papers/][format-bib.el]]
  - [[http://staff.science.uva.nl/~dominik/Tools/cdlatex/index.html][cdlatex.el]]

** Host-Names

Some settings as specific for certain platforms or host names. The
host names mentioned here are:

- gary
  - Debian GNU/Linux Wheezy
  - my main working horse

- blanche
  - OS X 10.5
  - pimped with [[https://www.macports.org/][MacPorts]]
  - (therefore) not as "capable" as gary

- grmlvrs
  - Debian GNU/Linux stable 5.0
  - (therefore) not as "capable" as gary

** Useful References

- http://www.emacswiki.org/emacs/CategoryDotEmacs
- http://www.emacswiki.org/emacs/LoadPath
  - ~/.emacs.d/lisp/ seems to be quite common as directory path for
    installing external packages
  - However, I do prefer "contrib" instead of "lisp" because:
    - my own config (outside of ~/.emacs.d/lisp/) is LISP as well
    - "lisp" does not contain the notion of "contributed from other people/projects"

** License

The code provided here is licensed under a GPL v3 license: see
license.txt for details. Some smaller parts from other authors but
included in my configuration might have a different license. Please
check the source - it's included in the comments.


